package com.hcs.entity;
// Generated 2017-7-18 1:03:45 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * AcctRoleAuthority generated by hbm2java
 */
@Entity
public class AcctRoleAuthority implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer roleId;
	private Integer acthorityId;

	public AcctRoleAuthority() {
	}

	public AcctRoleAuthority(Integer roleId, Integer acthorityId) {
		this.roleId = roleId;
		this.acthorityId = acthorityId;
	}

	@Id
	@Column(name = "id",unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "roleId", nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "acthorityId", nullable = false)
	public Integer getActhorityId() {
		return this.acthorityId;
	}

	public void setActhorityId(Integer acthorityId) {
		this.acthorityId = acthorityId;
	}

}
